# Generated by Django 3.0.10 on 2020-11-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubEx', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='likes',
        ),
        migrations.AddField(
            model_name='exercise',
            name='stars',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uservidwatch',
            name='joined_user',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='uservidwatch',
            name='joined_video',
            field=models.PositiveIntegerField(),
        ),
    ]
