# Generated by Django 3.0.10 on 2020-11-07 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubEx', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
